version: "3.3"

networks:
  frontend:
    external: true
  backend:
  
services:
  ghost:
    image: ghost:latest
    restart: always
    container_name: ghost-app
    depends_on:
      - db
    environment:
      url: https://domain.com
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__port: 3306
      database__connection__user: ghostuser
      database__connection__password: DBPASSWORD
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__host: host.domain.com
      mail__options__port: 587
      mail__options__auth__user: smtp.username
      mail__options__auth__pass: smtp.password
      mail__from: Example Corpo <mail@domain.com>
    volumes:
      - ./content:/var/lib/ghost/content
    networks:
      - frontend
      - backend

  db:
    image: mysql:latest
    restart: always
    container_name: ghost-db
    environment:
      MYSQL_ROOT_PASSWORD: DBPASSWORDROOT
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD: DBPASSWORD
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
